apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-hilltop-metrics
  namespace: monitoring
  labels:
    app: devops-hilltop
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devops-platform
  namespaceSelector:
    matchNames:
    - devops-hilltop
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-metrics
  namespace: monitoring
  labels:
    app: node-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-metrics
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      component: server
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true