apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-hilltop-config
  namespace: devops-hilltop
  labels:
    app: devops-platform
data:
  NODE_ENV: "production"
  PORT: "5000"
  APP_NAME: "DevOps with Hilltop"