apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-hilltop.fullname" . }}-secret
  labels:
    {{- include "devops-hilltop.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}